---
fail_fast: true

repos:
  - repo: local # Replace if https://github.com/get-alex/alex/pull/321 is merged
    hooks:
      - id: alex-js
        name: Alex.js
        description: Find gender favoring, polarizing, race related, religion inconsiderate, or other unequal phrasing in text.
        entry: alex
        language: node
        types:
          - markdown
        additional_dependencies:
          - alex
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.1.0
    hooks:
      - id: commitlint
        stages:
          - commit-msg
        additional_dependencies:
          - "@dwp/commitlint-config-base"
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.3
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.0.0-alpha.2
          - eslint-config-prettier
          - stylelint-config-prettier
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-vcs-permalinks # GitHub only, need to include GitLab
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: no-commit-to-branch
        args:
          - --branch=main
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: forbid-binary
      - id: shellcheck
        args: ["--severity=warning"] # Optionally only show errors and warnings
      - id: shfmt
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.12.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.15.0
    hooks:
      - id: gitleaks
