---
default_install_hook_types:
  - pre-commit
  - commit-msg

fail_fast: true

repos:
  - repo: https://gitlab.com/repo-hooks/pre-commit-community-health
    rev: v1.0.0-alpha # Use the ref you want to point at
    hooks:
      - id: block-commit-no-verify
